replicaCount: 2

image:
  repository: lab/subnet-calculator
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  # EKS Auto Mode Network Load Balancer
  loadBalancerClass: eks.amazonaws.com/nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi
